### ISSUE TITLE
Añadir Personajes

### ISSUE THREAD

**Issue by Arion-J** [Arion-J/Novel#1]
Añadir todos los personajes que actualmente no están.
Ahora mismo, están:
- Lorenzo
- Gustavo

**Comment by ghost** [comment]
Stella añadida

**Comment by ghost** [comment]
Daniel añadido

**Comment by ghost** [comment]
Aurelia Añadida

**Comment by ghost** [comment]
Diego añadido

**Comment by ghost** [comment]
Valentino añadido

**Comment by ghost** [comment]
Jon añadido

**Comment by ghost** [comment]
Oso añadido

**Comment by ghost** [comment]
Osa añadida

**Comment by ghost** [comment]
Azzura añadida

**Comment by ghost** [comment]
Piera añadida

**Comment by ghost** [comment]
Kido añadido

**Comment by ghost** [comment]
Kageyama añadido

**Comment by ghost** [comment]
Demonio añadido

**Comment by ghost** [comment]
Violette añadido

**Comment by Arion-J** [comment]
Terminado, cierro el issue
